spring:
  application:
    name: redis-demo-application

  datasource:
    url: jdbc:postgresql://localhost:5432/redisdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  # redis-cli key for communication to redis cloud through url
  data:
    redis:
      url: redis://default:vJuXzDXSSdD3vLOdqdWBhGjjJWUSW1bT@specular-idealistic-coherent-42246.db.redis.io:10112

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # TTL (Time To Live): The amount of time a key remains available in Redis before it expires.
redis:
  cache:
    ttl: 600

logging:
  level:
    root: INFO
    com.redis: DEBUG