spring:
  application:
    name: redis-demo-application0


  datasource:
    url: jdbc:postgresql://localhost:5432/redisdb
    username: redis
    password: postgres
    driver-class-name: org.postgresql.Driver


  redis:
    host: localhost
    port: 6379
    cache:
      user-ttl: 600

  logging:
    level:
      root: INFO
      com.redis: DEBUG